### ISSUE TITLE
Build submenu

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/kiroletik#39]

**Comment by unaizalakain** [comment]
OK, now pressing "Others" toggles the "active" class on the subnav.

Now that you put the little arrow on Others, what do you think about moving Others to the right end of the nav, so that it's the last element? The arrow would make more sense there right?

**Comment by iunetrecet** [comment]
The active class should be in the li, not in the submenu

**Comment by unaizalakain** [comment]
The `active` class is now toggled on li#others

**Comment by iunetrecet** [comment]
Now the submenu is displayed all the time

**Comment by unaizalakain** [comment]
Isn't that because it isn't hidden with css when the active class isn't present?

**Comment by iunetrecet** [comment]
It doesn't change when you click in the link

**Comment by unaizalakain** [comment]
I checked twice... The `active` class is toggled when you click on others, please confirm.
