### ISSUE TITLE
The title on the aside doesn't make much sense

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/kiroletik#47]

**Comment by unaizalakain** [comment]
The panel shows a list of championships and inside every one of them a list of its seasons. But the title for it is "Matches" witch I think it doesn't make much sense.

**Comment by iunetrecet** [comment]
Closed #47: Removed title of the aside championship list

**Comment by unaizalakain** [comment]
As noted in 26c300fdf2046194913a4ae1dbae675d80ffae0c, the aside is now defined in `base.html`.

**Comment by iunetrecet** [comment]
But I saw that and removed
